http:
  routers:
    autosheets:
      rule: "Host(`autosheets.loudigital.shop`)"
      entryPoints:
        - "websecure"
      service: "autosheets"
      tls:
        certResolver: "letsencryptresolver"

  services:
    autosheets:
      loadBalancer:
        servers:
          - url: "http://31.97.168.36:8080"