name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        timeout: 300s
        script: |
          cd /root/autosheets
          
          # Pull latest changes
          git fetch origin
          git reset --hard origin/main
          
          # Make deploy script executable
          chmod +x deploy-production.sh
          
          # Run deployment
          ./deploy-production.sh